package com.rollingstone.command;

public enum GenericCommandType {

	CREATE_USER_PROFILE,
	UPDATE_USER_PROFILE, 
	CREATE_PRODUCT,
	UPDATE_PRODUCT,
	CREATE_SHIPPING,
	UPDATE_SHIPPING,
	CREATE_CATEGORY,
	UPDATE_CATEGORY,
	CREATE_DELIVERY,
	UPDATE_DELIVERY,
	CREATE_CHECKOUT,
	UPDATE_CHECKOUT,
	ADD_TO_CART,
	UPDATE_CART,
	REMOVE_FROM_CART,
	CREATE_PAYMENT,
	UPDATE_PAYMENT,
	CREATE_ACCOUNT,
	UPDATE_ACCOUNT,
	CREATE_ADDRESS,
	UPDATE_ADDRESS,
	CREATE_PRODUCT_RATING, 
	UPDATE_PRODUCT_RATING, 
	CREATE_SPU,
	UPDATE_SPU,
	DEBUG,
	CREATE_TODO,
	UPDATE_TODO,
	DELETE_TODO

}
